In [1]:
import os, math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

le = LabelEncoder()
seed = np.random.seed
enc = OneHotEncoder()

In [2]:
# Wczytanie danych mushrooms.csv
df = pd.read_csv('mushrooms.csv')
display(df)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [3]:
# df.info()

In [5]:
# Wartosci wejsciowe
X = df.drop(columns=['class'], axis=1)
# Zapisanie klas grzybow (jadalne, niejadalne)
y = df['class']
display(X)
display(y)

cap-shape cap-surface cap-color bruises odor gill-attachment  \
0            x           s         n       t    p               f   
1            x           s         y       t    a               f   
2            b           s         w       t    l               f   
3            x           y         w       t    p               f   
4            x           s         g       f    n               f   
...        ...         ...       ...     ...  ...             ...   
8119         k           s         n       f    n               a   
8120         x           s         n       f    n               a   
8121         f           s         n       f    n               a   
8122         k           y         n       f    y               f   
8123         x           s         n       f    n               a   

     gill-spacing gill-size gill-color stalk-shape  ...  \
0               c         n          k           e  ...   
1               c         b          k           e  ...   
2               c         b          n           e  ...   
3               c         n          n           e  ...   
4               w         b          k           t  ...   
...           ...       ...        ...         ...  ...   
8119            c         b          y           e  ...   
8120            c         b          y           e  ...   
8121            c         b          n           e  ...   
8122            c         n          b           t  ...   
8123            c         b          y           e  ...   

     stalk-surface-below-ring stalk-color-above-ring stalk-color-below-ring  \
0                           s                      w                      w   
1                           s                      w                      w   
2                           s                      w                      w   
3                           s                      w                      w   
4                           s                      w                      w   
...                       ...                    ...                    ...   
8119                        s                      o                      o   
8120                        s                      o                      o   
8121                        s                      o                      o   
8122                        k                      w                      w   
8123                        s                      o                      o   

     veil-type veil-color ring-number ring-type spore-print-color population  \
0            p          w           o         p                 k          s   
1            p          w           o         p                 n          n   
2            p          w           o         p                 n          n   
3            p          w           o         p                 k          s   
4            p          w           o         e                 n          a   
...        ...        ...         ...       ...               ...        ...   
8119         p          o           o         p                 b          c   
8120         p          n           o         p                 b          v   
8121         p          o           o         p                 b          c   
8122         p          w           o         e                 w          v   
8123         p          o           o         p                 o          c   

     habitat  
0          u  
1          g  
2          m  
3          u  
4          g  
...      ...  
8119       l  
8120       l  
8121       l  
8122       l  
8123       l  

[8124 rows x 22 columns]

0       p
1       e
2       e
3       p
4       e
       ..
8119    e
8120    e
8121    e
8122    p
8123    e
Name: class, Length: 8124, dtype: object

In [7]:
# Zakodowanie numerow klas wedlug goracej jedynki 
x = enc.fit_transform(X).toarray()
display(x.shape)
display(x)
# Zmiana nazw klas na liczby
y = le.fit_transform(y)
display(y.shape)
display(y)

(8124, 117)

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

(8124,)

array([1, 0, 0, ..., 0, 1, 0], dtype=int32)

In [8]:
# Podzial na wartosci do trenowania i testowania
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)
display(x_train, y_train)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [7]:
# Perceptron wielowarstwowy
mlp = MLPClassifier(alpha=0.1, hidden_layer_sizes=60, learning_rate_init=0.1,
              max_iter=1000, random_state=1, solver='lbfgs', verbose=10)
mlp.out_activation = 'softmax'

In [8]:
# Parametramy ktore posluza nam do znalezienia najlepszego klasyfikatora
parametry = {'learning_rate_init' : (0.1, 0.01, 0.001), 'hidden_layer_sizes' : [20, 40, 60, 80, 100], 
            'solver' : ['adam', 'lbfgs', 'sgd']}
# Siatka do przeszukiwania podanych parametrow
clf = GridSearchCV(mlp, parametry)

In [9]:
clf.fit(x, y)

Iteration 1, loss = 0.13224266
Iteration 2, loss = 0.04641125
Iteration 3, loss = 0.02197856
Iteration 4, loss = 0.01601985
Iteration 5, loss = 0.01322489
Iteration 6, loss = 0.01181752
Iteration 7, loss = 0.01507871
Iteration 8, loss = 0.02219789
Iteration 9, loss = 0.01728260
Iteration 10, loss = 0.01290325
Iteration 11, loss = 0.01337601
Iteration 12, loss = 0.01403639
Iteration 13, loss = 0.01739473
Iteration 14, loss = 0.03058362
Iteration 15, loss = 0.01647977
Iteration 16, loss = 0.01422199
Iteration 17, loss = 0.01303225
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
Iteration 1, loss = 0.15219207
Iteration 2, loss = 0.04488711
Iteration 3, loss = 0.02136668
Iteration 4, loss = 0.01473008
Iteration 5, loss = 0.01463130
Iteration 6, loss = 0.01299988
Iteration 7, loss = 0.01888597
Iteration 8, loss = 0.01296232
Iteration 9, loss = 0.01221350
Iteration 10, loss = 0.01293839
Iteration 11, loss = 0.01565709
Iteration 12, loss = 0.01381800


GridSearchCV(estimator=MLPClassifier(alpha=0.1, hidden_layer_sizes=60,
                                     learning_rate_init=0.1, max_iter=1000,
                                     random_state=1, solver='lbfgs',
                                     verbose=10),
             param_grid={'hidden_layer_sizes': [20, 40, 60, 80, 100],
                         'learning_rate_init': (0.1, 0.01, 0.001),
                         'solver': ['adam', 'lbfgs', 'sgd']})

In [10]:
# display(clf.cv_results_)

In [11]:
print("Dokladnosc dla GridSearcha: " + str(clf.score(x, y)*100) + "%")
print("Najlepsze parametry:  " + str(clf.best_params_))

Dokladnosc dla danych treningowych: 100.0%
Dokladnosc dla danych testowych: 100.0%
Najlepsze parametry:  {'hidden_layer_sizes': 60, 'learning_rate_init': 0.1, 'solver': 'lbfgs'}


In [12]:
# Perceptron wielowarstwowy dla najlepszych parametrow
mlp2 = MLPClassifier(alpha=0.1, hidden_layer_sizes=clf.best_params_['hidden_layer_sizes'], 
                    learning_rate_init=clf.best_params_['learning_rate_init'],
                    max_iter=1000, random_state=1, solver=clf.best_params_['solver'])
mlp2.out_activation = 'softmax'

In [ ]:
# Trening Perceptrona z najlepszymi wartosciami
mlp2.fit(x_train, y_train)

In [29]:
# Trening
mlp2.predict(x_train)

array([0, 0, 0, ..., 0, 0, 0])

In [30]:
print("Dokladnosc dla danych treningowych: " + str(mlp2.score(x_train, y_train)*100) + "%")
print("Dokladnosc dla danych testowych: " + str(mlp2.score(x_test, y_test)*100) + "%")

Dokladnosc dla danych treningowych: 100.0%
Dokladnosc dla danych testowych: 100.0%


In [26]:
# Wykres
x_label = []
for x in range(len(mlp2.loss_curve_)):
    x_label.append(x)
plt.plot(x_label, mlp2.loss_curve_)
plt.grid(which='both')
plt.title('Loss curve')
plt.xlabel('Number of iterations')
plt.ylabel('Numerical value')
plt.show()

AttributeError: 'MLPClassifier' object has no attribute 'loss_curve_'

In [27]:
# Raport klasyfikacji
y_true, y_pred = y_test, clf.predict(x_test)
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       852
           1       1.00      1.00      1.00       773

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625

